# -*- coding: utf-8 -*-
"""Parcial3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtTxs_4TwmomSDvzPIaGgDLxnTY0xFNB
"""

from ast import Str


class User:
  def _init_(self, userId:str, resgistrerDate:int, password:int):
    
    self.userId = UserId
    self.resgistrerDate = ResgistrerDate
    self.password =Password

class Customer:
  def _init_(self, name:str, addres:int, email:str, customerId:str, accountBalance:int):
    self.name=Name
    self.address=Address
    self.email:Email
    self.customerId:CustomerId
    self.accountBalance=AccountBalance

class Adimistrator:
  def _init_(self, name:str, email:str):

    self.name=Name
    self.email=Email

class Order:
  def _init_ (self, orderId:str, date:date, customerName:str, customerId:int):

    self.orderId=OrderId
    self.date=Date
    self.customerName=CustomerName
    self.customerId= CustomerId

class OrderDetails:
  def _init_ (self, orderId:int, productId:int, productName:str, quantity:int, unitCost:int, total:int):

    self.orderId = OrderId
    self.productId = ProductId
    self.productName = ProductName
    self.quantity = Quantity
    self.unitCost = UnitCost
    self.total = Total