# -*- coding: utf-8 -*-
"""Parcial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBr8xzB-RAtBy7ZbO8-AwYJ0AlPrkIRs
"""

from ast import Str


class Persona:
    def _init_(self, nombre:str, nif:int, fechaNac:int):

        self.nombre = Nombre
        self.nif=Nif
        self.fechaNac =Fecha(int)

class Jugador:
    def _init_(self, numFed:int,):
        self.numFed=numFed